#!/usr/bin/env python3
"""Regenerate app/.../ui/ServiceLogos.kt from Sonos's own list of services.

https://support.sonos.com/en-us/services carries every service Sonos lists, each with its logo,
as JSON records inside the page ({"_id", "slug", "title", "logo": {"asset": {"_ref": ...}}}).
A logo's ref `image-<hash>-<w>x<h>-<ext>` is served at media.sonos.com, which also scales and
converts on request (`?w=112&fm=png` turns the few SVGs into PNG, which Coil here can decode).

    python3 tools/service-logos.py
"""
import html
import json
import pathlib
import re
import urllib.request

PAGE = "https://support.sonos.com/en-us/services"
OUT = pathlib.Path(__file__).resolve().parent.parent / "app/src/main/java/com/rahga/x2rock/ui/ServiceLogos.kt"

request = urllib.request.Request(PAGE, headers={"User-Agent": "Mozilla/5.0"})
text = html.unescape(urllib.request.urlopen(request, timeout=30).read().decode()).replace('\\"', '"')
decoder = json.JSONDecoder()
logos = {}
for match in re.finditer(r'\{"_id":"', text):
    try:
        record, _ = decoder.raw_decode(text, match.start())
    except ValueError:
        continue
    ref = (record.get("logo") or {}).get("asset", {}).get("_ref")
    if not ref or "title" not in record:
        continue
    _, digest, size, ext = ref.split("-")
    logos.setdefault(record["title"], f"https://media.sonos.com/images/znqtjj88/production/{digest}-{size}.{ext}")

def kt(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'

rows = "\n".join(f"    {kt(title)} to {kt(url)}," for title, url in sorted(logos.items(), key=lambda kv: kv[0].lower()))
OUT.write_text(f'''package com.rahga.x2rock.ui

// Generated by tools/service-logos.py from {PAGE}. Do not edit; run the script again.

/** Each service's logo as Sonos lists it, by the name Sonos gives it there. See [serviceLogo]. */
internal val SERVICE_LOGOS: Map<String, String> = mapOf(
{rows}
)
''')
print(f"{len(logos)} logos -> {OUT}")
